# Generated by Django 3.2.5 on 2021-07-29 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210728_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='users_books',
            new_name='users',
        ),
    ]
